const SET_INITIALLIZED = "SET_INITIALLIZED";
const SET_AUTH_USER = "SET_AUTH_USER";
const TOGGLE_BAR = "TOGGLE_BAR";
const SET_PROFILE = 'SET_PROFILE';
const ADD_MESSAG = "ADD_MESSAG";
const ADD_POST = 'ADD_POST';
const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
const SET_CURRENT_STATUS = 'SET_CURRENT_STATUS';
const DELETE_POST = 'DELETE_POST';
const FOLLOW = 'FOLLOW';
const UNFOLLOW = 'UNFOLLOW';
const SET_USERS = 'SET_USERS';
const SET_MY_PROFILE = 'SET_MY_PROFILE';
const SET_TOTAL_COUNT_PAGE = 'SET_TOTAL_COUNT_PAGE';
const SET_LENGTH_COUNT_PAGE = 'SET_LENGTH_COUNT_PAGE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const TOGGLE_ISLOADER = 'TOGGLE_ISLOADER';
const TOGGLE_DISABLED_FOLLOW = 'TOGGLE_DISABLED_FOLLOW';
const SET_TOP_FRIENDS = 'SET_TOP_FRIENDS';
const SAVE_PHOTO = 'SAVE_PHOTO';
const IS_MY_PAGES = 'IS_MY_PAGES';
const UPDATE_MY_INFO = 'UPDATE_MY_INFO';
const GET_CAPTCHA = 'GET_CAPTCHA';

export {
  SET_INITIALLIZED,
  UPDATE_MY_INFO,
  SET_AUTH_USER,
  TOGGLE_BAR,
  SET_PROFILE,
  SET_MY_PROFILE,
  ADD_MESSAG,
  ADD_POST,
  GET_CAPTCHA,
  SAVE_PHOTO,
  SET_CURRENT_PROFILE,
  SET_CURRENT_STATUS,
  DELETE_POST,
  FOLLOW,
  UNFOLLOW,
  SET_USERS,
  SET_TOTAL_COUNT_PAGE,
  SET_LENGTH_COUNT_PAGE,
  SET_CURRENT_PAGE,
  TOGGLE_ISLOADER,
  TOGGLE_DISABLED_FOLLOW,
  SET_TOP_FRIENDS,
  IS_MY_PAGES,
}